# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_RESTDB_API_KEY: ${{ secrets.REACT_APP_RESTDB_API_KEY }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REACT_APP_RESTDB_API_KEY: ${{ secrets.REACT_APP_RESTDB_API_KEY }}
        BRANCH: gh-pages
        FOLDER: build

